################################################################################
# Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################
---
name: Publish

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: The version you want to release
        required: true
        type: string
      developmentVersion:
        description: The development version to assign after the release
        required: true
        type: string
  # only committers can trigger this
jobs:
  publish-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: temurin

      # consider configuring git user

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5.0.0
        with:
          gpg_private_key: ${{ secrets.ORG_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.ORG_GPG_PASSPHRASE }}

      - name: Publish to Maven
        env:
          # used in settings.xml
          MAVEN_USERNAME: ${{ secrets.ORG_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ORG_OSSRH_PASSWORD }}
        # command summary
        # -B/--batch-mode: only display progress and errors
        # -U: update snapshot-releases
        # -Pci-cd: apply the ci-cd profile (in pom.xml)
        # release:prepare (comes from maven-release-plugin)
        # release:perform (comes from maven-release-plugin)
        # javadoc:jar: checks documentation strings
        # source:jar: creates a <lib>-<version>-source.jar
        # -s settings.xml: use custom settings file
        # -D gpg.passphrase: a system property used by the build process for signing
        # -D releaseVeresion: set the version you're releasing (will also tag using this)
        # -D developmentVersion: set the next dev version
        run: |-
          echo "Publishing using version: ${{ inputs.version }}"
          ./mvnw -B -U \
            -Pci-cd \
            release:prepare \
            release:perform \
            javadoc:jar \
            source:jar \
            -s settings.xml \
            -D gpg.passphrase=${{ secrets.ORG_GPG_PASSPHRASE }} \
            -D releaseVersion=${{ inputs.releaseVersion }} \
            -D developmentVersion=${{ inputs.developmentVersion }} \
            deploy
